# Copyright 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: Automatically generated by files-by-owner.sh, do not edit
#

#  blob(s) necessary for Harris Beach hardware
PRODUCT_COPY_FILES := \
    vendor/intel_oblumg/hsb/proprietary/disable_houdini:system/bin/disable_houdini:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/enable_houdini:system/bin/enable_houdini:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/houdini:system/bin/houdini:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/check.xml:system/lib/arm/check.xml:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/cpuinfo:system/lib/arm/cpuinfo:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/cpuinfo.neon:system/lib/arm/cpuinfo.neon:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libandroidfw.so:system/lib/arm/libandroidfw.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libandroid_runtime.so:system/lib/arm/libandroid_runtime.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libandroid.so:system/lib/arm/libandroid.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libaudioflinger.so:system/lib/arm/libaudioflinger.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libaudioutils.so:system/lib/arm/libaudioutils.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libbcc.so:system/lib/arm/libbcc.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libbcinfo.so:system/lib/arm/libbcinfo.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libbinder.so:system/lib/arm/libbinder.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcamera_client.so:system/lib/arm/libcamera_client.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcamera_metadata.so:system/lib/arm/libcamera_metadata.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcommon_time_client.so:system/lib/arm/libcommon_time_client.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libconnectivitymanager.so:system/lib/arm/libconnectivitymanager.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libc_orig.so:system/lib/arm/libc_orig.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcorkscrew.so:system/lib/arm/libcorkscrew.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcrypto.so:system/lib/arm/libcrypto.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libc.so:system/lib/arm/libc.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libcutils.so:system/lib/arm/libcutils.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libdl.so:system/lib/arm/libdl.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libdrmframework.so:system/lib/arm/libdrmframework.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libdvm.so:system/lib/arm/libdvm.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libeffects.so:system/lib/arm/libeffects.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libEGL.so:system/lib/arm/libEGL.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libETC1.so:system/lib/arm/libETC1.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libexpat.so:system/lib/arm/libexpat.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libfilterfw.so:system/lib/arm/libfilterfw.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libfilterpack_imageproc.so:system/lib/arm/libfilterpack_imageproc.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libft2.so:system/lib/arm/libft2.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libgabi++.so:system/lib/arm/libgabi++.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libgccdemangle.so:system/lib/arm/libgccdemangle.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libGLESv1_CM.so:system/lib/arm/libGLESv1_CM.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libGLESv2.so:system/lib/arm/libGLESv2.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libgui.so:system/lib/arm/libgui.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libhardware_legacy.so:system/lib/arm/libhardware_legacy.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libhardware.so:system/lib/arm/libhardware.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libharfbuzz_ng.so:system/lib/arm/libharfbuzz_ng.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libharfbuzz.so:system/lib/arm/libharfbuzz.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libhwui.so:system/lib/arm/libhwui.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libicui18n.so:system/lib/arm/libicui18n.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libicuuc.so:system/lib/arm/libicuuc.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libinput.so:system/lib/arm/libinput.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libjnigraphics.so:system/lib/arm/libjnigraphics.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libjpeg.so:system/lib/arm/libjpeg.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libLLVM.so:system/lib/arm/libLLVM.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/liblog.so:system/lib/arm/liblog.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libmedia.so:system/lib/arm/libmedia.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libmemtrack.so:system/lib/arm/libmemtrack.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libm_orig.so:system/lib/arm/libm_orig.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libm.so:system/lib/arm/libm.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libnativehelper.so:system/lib/arm/libnativehelper.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libnbaio.so:system/lib/arm/libnbaio.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libnetutils.so:system/lib/arm/libnetutils.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libnfc_ndef.so:system/lib/arm/libnfc_ndef.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libOpenMAXAL.so:system/lib/arm/libOpenMAXAL.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libOpenSLES.so:system/lib/arm/libOpenSLES.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libpixelflinger.so:system/lib/arm/libpixelflinger.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libpng.so:system/lib/arm/libpng.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libpowermanager.so:system/lib/arm/libpowermanager.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libRScpp.so:system/lib/arm/libRScpp.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libRSDriver.so:system/lib/arm/libRSDriver.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libRS.so:system/lib/arm/libRS.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libselinux.so:system/lib/arm/libselinux.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libskia.so:system/lib/arm/libskia.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libsonivox.so:system/lib/arm/libsonivox.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libspeexresampler.so:system/lib/arm/libspeexresampler.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libsqlite.so:system/lib/arm/libsqlite.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libssl.so:system/lib/arm/libssl.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright_avc_common.so:system/lib/arm/libstagefright_avc_common.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright_enc_common.so:system/lib/arm/libstagefright_enc_common.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright_foundation.so:system/lib/arm/libstagefright_foundation.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright_omx.so:system/lib/arm/libstagefright_omx.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright.so:system/lib/arm/libstagefright.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstagefright_yuv.so:system/lib/arm/libstagefright_yuv.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstdc++.so:system/lib/arm/libstdc++.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libstlport.so:system/lib/arm/libstlport.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libsurfaceflinger.so:system/lib/arm/libsurfaceflinger.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libsync.so:system/lib/arm/libsync.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libui.so:system/lib/arm/libui.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libusbhost.so:system/lib/arm/libusbhost.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libutils.so:system/lib/arm/libutils.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvideoeditor_core.so:system/lib/arm/libvideoeditor_core.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvideoeditor_jni.so:system/lib/arm/libvideoeditor_jni.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvideoeditor_osal.so:system/lib/arm/libvideoeditor_osal.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvideoeditorplayer.so:system/lib/arm/libvideoeditorplayer.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvideoeditor_videofilters.so:system/lib/arm/libvideoeditor_videofilters.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libvorbisidec.so:system/lib/arm/libvorbisidec.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libwebrtc_audio_coding.so:system/lib/arm/libwebrtc_audio_coding.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libwpa_client.so:system/lib/arm/libwpa_client.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libz.so:system/lib/arm/libz.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/linker:system/lib/arm/linker:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libhoudini.so:system/lib/libhoudini.so:intel_oblumg \
    vendor/intel_oblumg/hsb/proprietary/libhoudini.so.4.0.0.44205:system/lib/libhoudini.so.4.0.0.44205:intel_oblumg \

