# Copyright 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: Automatically generated by files-by-owner.sh, do not edit
#

#  blob(s) necessary for Harris Beach hardware
PRODUCT_COPY_FILES := \
    vendor/intel_apache/hsb/proprietary/com.google.widevine.software.drm.xml:system/etc/permissions/com.google.widevine.software.drm.xml:intel_apache \
    vendor/intel_apache/hsb/proprietary/audio.primary.aosp_hsb.so:system/lib/hw/audio.primary.aosp_hsb.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/camera.aosp_hsb.so:system/lib/hw/camera.aosp_hsb.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/hwcomposer.default.so:system/lib/hw/hwcomposer.default.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libI420colorconvert.so:system/lib/libI420colorconvert.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoDecoderAVCSecure.so:system/lib/libOMXVideoDecoderAVCSecure.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoDecoderAVC.so:system/lib/libOMXVideoDecoderAVC.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoDecoderH263.so:system/lib/libOMXVideoDecoderH263.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoDecoderMPEG4.so:system/lib/libOMXVideoDecoderMPEG4.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoDecoderWMV.so:system/lib/libOMXVideoDecoderWMV.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoEncoderH263.so:system/lib/libOMXVideoEncoderH263.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libOMXVideoEncoderMPEG4.so:system/lib/libOMXVideoEncoderMPEG4.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libpavp.so:system/lib/libpavp.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libsecvideoparser.so:system/lib/libsecvideoparser.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libwrs_omxil_common.so:system/lib/libwrs_omxil_common.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libwrs_omxil_core_pvwrapped.so:system/lib/libwrs_omxil_core_pvwrapped.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libbt-vendor.so:system/vendor/lib/libbt-vendor.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libwvm.so:system/vendor/lib/libwvm.so:intel_apache \
    vendor/intel_apache/hsb/proprietary/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so:intel_apache \

