# Copyright 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: Automatically generated by files-by-owner.sh, do not edit
#

#  blob(s) necessary for Harris Beach hardware
PRODUCT_COPY_FILES := \
    vendor/intel_oblsla/hsb/proprietary/libWVCrypto.so:system/lib/libWVCrypto.so:intel_oblsla \

