# Copyright 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: Automatically generated by files-by-owner.sh, do not edit
#

#  blob(s) necessary for Harris Beach hardware
PRODUCT_COPY_FILES := \
    vendor/intel_obl/hsb/proprietary/coreu:system/bin/coreu:intel_obl \
    vendor/intel_obl/hsb/proprietary/curd:system/bin/curd:intel_obl \
    vendor/intel_obl/hsb/proprietary/hdcpd:system/bin/hdcpd:intel_obl \
    vendor/intel_obl/hsb/proprietary/mediainfo:system/bin/mediainfo:intel_obl \
    vendor/intel_obl/hsb/proprietary/ufo.prop:system/etc/ufo.prop:intel_obl \
    vendor/intel_obl/hsb/proprietary/libGLES_intel7_5.so:system/lib/egl/libGLES_intel7_5.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libGLES_intel.so:system/lib/egl/libGLES_intel.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/gralloc.haswell.so:system/lib/hw/gralloc.haswell.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/hwcomposer.haswell.so:system/lib/hw/hwcomposer.haswell.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/i965_drv_video.so:system/lib/i965_drv_video.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/igfxcmjit32.so:system/lib/igfxcmjit32.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/igfxcmrt32.so:system/lib/igfxcmrt32.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/lib2d.so:system/lib/lib2d.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libcoreuclient.so:system/lib/libcoreuclient.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libcoreuinterface.so:system/lib/libcoreuinterface.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libcoreuservice.so:system/lib/libcoreuservice.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libgabi++-mfx.so:system/lib/libgabi++-mfx.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libgrallocclient.so:system/lib/libgrallocclient.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libgrallocgmm.so:system/lib/libgrallocgmm.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libgsmgr.so:system/lib/libgsmgr.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libhwcservice.so:system/lib/libhwcservice.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libintelmetadatabuffer.so:system/lib/libintelmetadatabuffer.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libivp.so:system/lib/libivp.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libjpegdec.so:system/lib/libjpegdec.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmfxhw32.so:system/lib/libmfxhw32.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmfx_omx_components_hw.so:system/lib/libmfx_omx_components_hw.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmfx_omx_core.so:system/lib/libmfx_omx_core.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmixvbp_h264secure.so:system/lib/libmixvbp_h264secure.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmixvbp_h264.so:system/lib/libmixvbp_h264.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmixvbp_mpeg4.so:system/lib/libmixvbp_mpeg4.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmixvbp.so:system/lib/libmixvbp.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmixvbp_vc1.so:system/lib/libmixvbp_vc1.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libmix_videovpp.so:system/lib/libmix_videovpp.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libpavpdll.so:system/lib/libpavpdll.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libpcp.so:system/lib/libpcp.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libstagefrighthw.so:system/lib/libstagefrighthw.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libstlport-mfx.so:system/lib/libstlport-mfx.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libuevent.so:system/lib/libuevent.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libva_videodecoder.so:system/lib/libva_videodecoder.so:intel_obl \
    vendor/intel_obl/hsb/proprietary/libva_videoencoder.so:system/lib/libva_videoencoder.so:intel_obl \

